services:
  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  server:
    build: ./server
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

  client:
    build: ./client
    ports:
      - "5173:80"
    env_file: .env
    depends_on:
      - server
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo_data:
